service: coleus

provider:
  name: aws
  region: us-east-1
  stage: production
  runtime: provided
  environment:
    APP_ENV: production
    APP_DEBUG: false
    APP_KEY: ${ssm:/coleus/APP_KEY}
    DB_CONNECTION: ${ssm:/coleus/DB_CONNECTION}
    DB_HOST: ${ssm:/coleus/DB_HOST}
    DB_PORT: ${ssm:/coleus/DB_PORT}
    DB_DATABASE: ${ssm:/coleus/DB_DATABASE}
    DB_USERNAME: ${ssm:/coleus/DB_USERNAME}
    DB_PASSWORD: ${ssm:/coleus/DB_PASSWORD}
    IMGPROXY_KEY: ${ssm:/coleus/IMGPROXY_KEY}
    IMGPROXY_SALT: ${ssm:/coleus/IMGPROXY_SALT}
    IMGPROXY_PUBLIC_URL: ${ssm:/coleus/IMGPROXY_PUBLIC_URL}
    FILESYSTEM_DRIVER: s3
    FILESYSTEM_CLOUD: s3
    AWS_ACCESS_KEY_ID: ${ssm:/coleus/AWS_KEY}
    AWS_SECRET_ACCESS_KEY: ${ssm:/coleus/AWS_SECRET}
    AWS_DEFAULT_REGION: us-east-1
    AWS_BUCKET: coleus-public
    DATASET_BUCKET: coleus-data
  vpc:
    securityGroupIds:
      - sg-f012a9a8
    subnetIds:
      - subnet-37101638
      - subnet-d9392593
      - subnet-eb672eb7
      - subnet-67682349
      - subnet-5a74e464
      - subnet-f5276b92

package:
  exclude:
    - node_modules/**
    - public/storage
    - resources/assets/**
    - storage/**
    - tests/**

functions:
  web:
    handler: public/index.php
    timeout: 28
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - http: "ANY /"
      - http: "ANY /{proxy+}"
  artisan:
    handler: artisan
    timeout: 120
    layers:
      - ${bref:layer.php-74}
      - ${bref:layer.console}

plugins:
  - ./vendor/bref/bref

resources:
  Resources:
    WebsiteCDN:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          # Cheapest option by default (https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_DistributionConfig.html)
          PriceClass: PriceClass_100
          # Enable http2 transfer for better performances
          HttpVersion: http2
          # Origins are where CloudFront fetches content
          Origins:
            # The website (AWS Lambda)
            - Id: Website
              DomainName:
                !Join [
                  ".",
                  [
                    !Ref ApiGatewayRestApi,
                    "execute-api",
                    !Ref AWS::Region,
                    "amazonaws.com",
                  ],
                ]
              # This is the stage
              OriginPath: "/${opt:stage, 'production'}"
              CustomOriginConfig:
                OriginProtocolPolicy: "https-only" # API Gateway only supports HTTPS
          # The default behavior is to send everything to AWS Lambda
          DefaultCacheBehavior:
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            TargetOriginId: Website # the PHP application
            # Disable caching for the PHP application https://aws.amazon.com/premiumsupport/knowledge-center/prevent-cloudfront-from-caching-files/
            DefaultTTL: 0
            MinTTL: 0
            MaxTTL: 0
            # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-forwardedvalues.html
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all # Forward cookies to use them in PHP
              # We must *not* forward the `Host` header else it messes up API Gateway
              Headers:
                - "Accept"
                - "Accept-Language"
                - "Origin"
                - "Referer"
            ViewerProtocolPolicy: redirect-to-https
          CustomErrorResponses:
            # Do not cache HTTP errors
            - ErrorCode: 500
              ErrorCachingMinTTL: 0
            - ErrorCode: 504
              ErrorCachingMinTTL: 0
