service: laravel

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: dev
    runtime: provided
    environment:
        DB_HOST: ${ssm:/coleus/DB_HOST}
        DB_DATABASE: ${ssm:/coleus/DB_DATABASE}
        DB_USERNAME: ${ssm:/coleus/DB_USERNAME}
        DB_PASSWORD: ${ssm:/coleus/DB_PASSWORD}
        APP_ENV: production
        APP_DEBUG: true
        APP_KEY: "base64:GNfPMO7D5CmTP3ZTwTX8iznKJEHb9rHyFjhlxcern9c="

package:
    # Directories to exclude from deployment
    exclude:
        - node_modules/**
        - public/storage
        - resources/assets/**
        - storage/**
        - tests/**

functions:
    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: "ANY /"
            - http: "ANY /{proxy+}"
    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-74} # PHP
            - ${bref:layer.console} # The "console" layer

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
