service: coleus

provider:
    name: aws
    region: us-east-1
    runtime: provided
    environment:
        APP_ENV: production
        APP_DEBUG: true
        APP_KEY: "base64:GNfPMO7D5CmTP3ZTwTX8iznKJEHb9rHyFjhlxcern9c="
    vpc:
        securityGroupIds:
            - sg-f012a9a8
        subnetIds:
            - subnet-37101638
            - subnet-d9392593
            - subnet-eb672eb7
            - subnet-67682349
            - subnet-5a74e464
            - subnet-f5276b92

package:
    exclude:
        - node_modules/**
        - public/storage
        - resources/assets/**
        - storage/**
        - tests/**

functions:
    web:
        handler: public/index.php
        timeout: 28
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: "ANY /"
            - http: "ANY /{proxy+}"
    artisan:
        handler: artisan
        timeout: 120
        layers:
            - ${bref:layer.php-74}
            - ${bref:layer.console}

plugins:
    - ./vendor/bref/bref
